version: '3'

services:
  nginx:
    image: jeleniep/nginx_ssl
    depends_on:
      - web
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    environment:
        WAIT_HOSTS: web:5000

  web:
    image: jeleniep/flask-safe
    depends_on:
      # - db
      - mongodb
    volumes:
      - ./secure_app:/var/www/app
    environment:
        WAIT_HOSTS: mongodb:27017

  db:
    image: redis

  mongodb:
    image: mongo
    restart: always
    container_name: 'my_mongo'
    environment: 
      - MONGO_INITDB_DATABASE=db
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - ./mongo-volume:/data/db
    ports:
        - "27017-27019:27017-27019"
